sudo: required

# NOTE: It is necessary to explicitly set the distribution to "trusty" due to
# the complex 'matrix: include:' logic below
# More information: https://github.com/travis-ci/travis-ci/issues/5448
dist: trusty

addons:
  postgresql: "9.4"

services:
  - docker
  - postgresql

language: python

env:
  global:
    - RESOLWE_POSTGRESQL_USER=postgres
    - RESOLWE_POSTGRESQL_PORT=5432
    - GIT_LFS_VERSION=1.2.1

# NOTE: Explicit Python versions make Travis job description more informative
matrix:
  include:
    - env: TOX_ENV=py27
      python: "2.7"
    - env: TOX_ENV=py34
      python: "3.4"
    - env: TOX_ENV=py35
      python: "3.5"
    - env: TOX_ENV=docs
      python: "3.5"
    - env: TOX_ENV=linters
      python: "3.5"
    - env: TOX_ENV=packaging
      python: "3.5"

before_install:
  # manually install git-lfs until it is pre-installed by Travis
  # (https://github.com/travis-ci/travis-ci/issues/3634)
  - wget -q https://github.com/github/git-lfs/releases/download/v$GIT_LFS_VERSION/git-lfs-linux-amd64-$GIT_LFS_VERSION.tar.gz -O git-lfs.tar.gz
  - mkdir -p $HOME/bin
  - tar -xf git-lfs.tar.gz
  - mv git-lfs-$GIT_LFS_VERSION/git-lfs $HOME/bin/
  - export PATH=$PATH:$HOME/bin/

install: pip install tox

before_script:
  # fetch Git LFS files from remote and checkout required working tree files
  - git lfs pull

script: tox -e $TOX_ENV

after_success:
 - pip install codecov
 - codecov -e TOX_ENV
