# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-30 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resolwe_bio_kb', '0002_alter_field_max_length'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='mapping',
            index_together=set([('source_db', 'source_id', 'target_db'), ('target_db', 'target_id')]),
        ),
    ]
