# Generated by Django 2.2.12 on 2020-06-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resolwe_bio_kb", "0009_full_text_search"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="feature", unique_together=set(),),
        migrations.AlterUniqueTogether(name="mapping", unique_together=set(),),
        migrations.AlterIndexTogether(name="mapping", index_together=set(),),
        migrations.AddIndex(
            model_name="mapping",
            index=models.Index(
                fields=[
                    "source_db",
                    "source_id",
                    "source_species",
                    "target_db",
                    "target_species",
                ],
                name="idx_feature_source_target",
            ),
        ),
        migrations.AddIndex(
            model_name="mapping",
            index=models.Index(
                fields=["target_db", "target_id", "target_species"],
                name="idx_feature_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="feature",
            constraint=models.UniqueConstraint(
                fields=("source", "feature_id", "species"),
                name="uniq_feature_source_feature_id_species",
            ),
        ),
        migrations.AddConstraint(
            model_name="mapping",
            constraint=models.UniqueConstraint(
                fields=(
                    "source_db",
                    "source_id",
                    "source_species",
                    "target_db",
                    "target_id",
                    "target_species",
                    "relation_type",
                ),
                name="uniq_mapping_source_target_type",
            ),
        ),
    ]
