# Generated by Django 2.2.12 on 2020-05-29 07:53
import os

from django.db import connection, migrations


def update_index(apps, schema_editor):
    with connection.cursor() as c:
        file_path = os.path.join(os.path.dirname(__file__), "triggers_feature.sql")
        with open(file_path) as fh:
            sql_statement = fh.read()
        c.execute(sql_statement)


class Migration(migrations.Migration):
    dependencies = [
        ("resolwe_bio_kb", "0011_feature_type_index"),
    ]

    operations = [
        migrations.RunPython(update_index),
        # Update existing entries.
        migrations.RunSQL("UPDATE resolwe_bio_kb_feature SET id=id;"),
    ]
