# Generated by Django 3.2.18 on 2023-02-27 12:33
import os

from django.db import connection, migrations


def update_index(apps, schema_editor):
    file_names = [
        "triggers_feature.sql",
        "triggers_feature_2.sql",
    ]
    with connection.cursor() as c:
        for file_name in file_names:
            file_path = os.path.join(os.path.dirname(__file__), file_name)
            with open(file_path) as fh:
                sql_statement = fh.read()
            c.execute(sql_statement)


class Migration(migrations.Migration):
    dependencies = [
        ("resolwe_bio_kb", "0013_update_feature_search"),
    ]

    operations = [
        migrations.RunPython(update_index),
        # Update existing entries.
        migrations.RunSQL("UPDATE resolwe_bio_kb_feature SET id=id;"),
    ]
