# Generated by Django 4.2.13 on 2024-07-15 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resolwe_bio_variants", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="variantcall",
            old_name="unfiltered_allele_depth",
            new_name="alternative_allele_depth",
        ),
    ]
