# Generated by Django 4.2.13 on 2024-09-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "resolwe_bio_variants",
            "0004_alter_variantannotation_clinical_diagnosis_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="variantannotation",
            name="clinical_diagnosis",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
