# Generated by Django 4.2.13 on 2024-09-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resolwe_bio_variants", "0005_alter_variantannotation_clinical_diagnosis"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variantannotation",
            name="clinvar_id",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="variantannotation",
            name="dbsnp_id",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
