# Generated by Django 4.2.13 on 2024-09-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resolwe_bio_variants", "0006_alter_variantannotation_clinvar_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variant",
            name="alternative",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="variant",
            name="reference",
            field=models.CharField(max_length=150),
        ),
    ]
