# Generated by Django 4.2.13 on 2024-09-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "resolwe_bio_variants",
            "0007_alter_variant_alternative_alter_variant_reference",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="variantannotation",
            name="clinical_diagnosis",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="variantannotationtranscript",
            name="annotation",
            field=models.TextField(),
        ),
    ]
