FROM docker.io/resolwebio/base:ubuntu-16.04

MAINTAINER Resolwe Bioinformatics authors https://github.com/genialis/resolwe-bio

# Force matplotlib backend to a headless one.
ENV MPLBACKEND Agg

# Additional files:
COPY assets/ /opt/resolwebio/assets/
