# Generated by Django 3.2.12 on 2022-03-06 22:34
import os

from django.db import connection, migrations


def load_sql(apps, schema_editor):
    file_names = [
        "resolwe_indexes_3.sql",
    ]
    with connection.cursor() as c:
        for file_name in file_names:
            file_path = os.path.join(os.path.dirname(__file__), file_name)
            with open(file_path) as fh:
                sql_statement = fh.read()
            c.execute(sql_statement)


class Migration(migrations.Migration):
    dependencies = [
        ("resolwe_bio", "0002_metadata_table_type"),
    ]

    operations = [
        migrations.RunPython(load_sql),
    ]
