# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resolwe_bio", "0003_fix_jsonfields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sample",
            options={
                "default_permissions": (),
                "permissions": (
                    ("view_sample", "Can view sample"),
                    ("edit_sample", "Can edit sample"),
                    ("share_sample", "Can share sample"),
                    ("download_sample", "Can download files from sample"),
                    ("add_sample", "Can add data objects to sample"),
                    ("owner_sample", "Is owner of the sample"),
                ),
            },
        ),
    ]
