# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 01:45
from __future__ import unicode_literals

from django.db import migrations
import versionfield


class Migration(migrations.Migration):

    dependencies = [
        ('resolwe_bio', '0005_make_date_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='version',
            field=versionfield.VersionField(default='0.0.0'),
        ),
    ]
