# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 20:26
from __future__ import unicode_literals

from django.core.management import call_command
from django.db import migrations


def load_relation_types(apps, schema_editor):
    call_command("loaddata", "relationtypes", verbosity=0)


class Migration(migrations.Migration):

    dependencies = [
        ('resolwe_bio', '0009_delete_sample'),
    ]

    operations = [
        migrations.RunPython(load_relation_types),
    ]
