# Generated by Django 3.1.12 on 2021-06-21 05:45
import os

from django.db import connection, migrations


def load_sql(apps, schema_editor):
    file_names = [
        "resolwe_indexes_2.sql",
    ]
    with connection.cursor() as c:
        for file_name in file_names:
            file_path = os.path.join(os.path.dirname(__file__), file_name)
            with open(file_path) as fh:
                sql_statement = fh.read()
            c.execute(sql_statement)


class Migration(migrations.Migration):

    dependencies = [
        ("resolwe_bio", "0014_star_index2"),
    ]

    operations = [
        migrations.RunPython(load_sql),
    ]
