#!/usr/bin/env python2

# Script for running gen_utils.gen_checkrc() utility function.
# For more information see its documentation.

if __name__ == "__main__":
    import sys
    from gen_utils import gen_checkrc

    print(gen_checkrc(*sys.argv[1:]))
